/* vgda-1.vapi generated by valac 0.46.1.87-af96b, do not modify. */

[CCode (gir_namespace = "Vgda", gir_version = "1")]
namespace Vgda {
	/**
	 * Implementation of {@link Vda.Connection} using GDA's providers
	 */
	[CCode (cheader_filename = "vgda.h")]
	public class GProvider : GLib.Object, Vda.Connection {
		protected string _cnc_string;
		protected string _provider;
		public GProvider ();
	}
}
